# values-argo.yaml

redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
    hosts:
      - argocd.example.com   # same as global.domain
  service:
    type: ClusterIP

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.example.com

certificate:
  enabled: true
